import { useState } from 'react';
import { colors, fonts } from '../styles/tokens.js';

function buildAINote(project) {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  const activePhase = project.phases.find(p => p.status === 'active' || p.status === 'awaiting-signoff');
  const completedToday = project.phases
    .flatMap(ph => ph.steps)
    .filter(s => s.status === 'complete' && s.completedAt && (Date.now() - new Date(s.completedAt)) < 86400000);
  const blockedSteps = project.phases.flatMap(ph => ph.steps).filter(s => s.status === 'blocked');
  const activeStep = activePhase?.steps.find(s => s.status === 'active');

  const fatDays = project.plannedFATDate
    ? Math.ceil((new Date(project.plannedFATDate) - now) / 86400000)
    : null;

  const fatLine = fatDays === null
    ? ''
    : fatDays <= 0
    ? `\nFAT STATUS: OVERDUE (${Math.abs(fatDays)}d past target) — customer coordination required`
    : `\nFAT STATUS: ${fatDays}d remaining (${project.plannedFATDate})`;

  const blockSection = blockedSteps.length > 0
    ? `\nACTIVE BLOCKERS (${blockedSteps.length}):\n` +
      blockedSteps.map(s =>
        `  • Step #${s.id} — ${s.name}\n    Category: ${s.blockerCategory || 'Unspecified'}\n    Reason: ${s.blockReason || '—'}\n    Action required: escalate to program manager if unresolved within 4h`
      ).join('\n')
    : '\nBLOCKERS: None — all steps clear';

  const completedSection = completedToday.length > 0
    ? `\nCOMPLETED THIS SHIFT (${completedToday.length} step${completedToday.length !== 1 ? 's' : ''}):\n` +
      completedToday.map(s => `  ✓ #${s.id} — ${s.name}${s.note ? ` ("${s.note}")` : ''}`).join('\n')
    : '\nCOMPLETED THIS SHIFT: 0 steps';

  const phaseContext = activePhase
    ? generatePhaseContext(activePhase, activeStep)
    : '\nNEXT STEPS: All phases complete — await final QA disposition.';

  return (
    `SHIFT HANDOFF — ${dateStr} · ${timeStr}` +
    `\nProgram: ${project.id} · ${project.name}` +
    `\nCustomer: ${project.customer} · Lead: ${project.leadTech}` +
    `\n${'─'.repeat(54)}` +
    `\nCURRENT PHASE: ${activePhase ? `Ph.${activePhase.id} — ${activePhase.name}` : 'Complete'}` +
    fatLine +
    completedSection +
    blockSection +
    phaseContext +
    `\n${'─'.repeat(54)}` +
    `\n✦ Generated by AI Shift Assistant · Review and edit before handoff`
  );
}

function generatePhaseContext(phase, activeStep) {
  const done = phase.steps.filter(s => s.status === 'complete').length;
  const total = phase.steps.length;
  const pct = Math.round((done / total) * 100);
  const nextLocked = phase.steps.find(s => s.status === 'locked');

  const phaseGuidance = {
    'Mechanical Assembly': [
      'Verify all bolt torque values logged per drawing callouts before advancing',
      'Confirm structural alignment — record critical dimensions in QA log',
      'Check all mechanical interlocks and limit switch actuations per test plan',
    ],
    'Electrical Integration': [
      'Verify continuity on all control signals with multimeter before energizing',
      'Torque all terminal connections per spec and label harnesses per wiring diagram',
      'Complete megger test on power circuits — record all insulation resistance values',
    ],
    'Software & Controls': [
      'Run pre-defined I/O checkout and capture output file in program records',
      'Confirm software revision matches released baseline in version control',
      'Verify all interlocks and E-stop circuits functional before full-stand power-up',
    ],
    'Calibration & Verification': [
      'Record calibration certificate numbers for all sensors installed this shift',
      'Verify zero-offset and span within tolerance per cal sheet — log any deviations',
      'Confirm data acquisition accuracy end-to-end before signing off calibration records',
    ],
    'Factory Acceptance Testing': [
      'All pre-FAT checklist items must be green before customer witness arrival',
      'Coordinate with QA for final as-built review and documentation package sign-off',
      'Confirm spare parts kit and calibration cert package are staged for customer delivery',
    ],
    'Shipping Prep & Documentation': [
      'Verify all fluid systems drained and flushed — all ports blanked and tagged',
      'Confirm packing list matches actual contents before crate seal',
      'Photograph all crated assemblies and retain in program file for delivery record',
    ],
  };

  const tips = phaseGuidance[phase.name] || [
    'Follow all drawing and routing specifications',
    'Log any deviations in quality system before advancing',
    'Confirm next step prerequisites are satisfied',
  ];

  return (
    `\n\nFOR INCOMING TECHNICIAN (Ph.${phase.id} — ${pct}% complete):` +
    (activeStep ? `\n  → In progress: Step #${activeStep.id} — ${activeStep.name}` : '') +
    (nextLocked ? `\n  → Next locked: Step #${nextLocked.id} — ${nextLocked.name}` : '') +
    `\n\nKEY REMINDERS FOR ${phase.name.toUpperCase()}:\n` +
    tips.map(t => `  • ${t}`).join('\n') +
    `\n\nHANDOFF CONFIRMED BY: ___________________ DATE/TIME: ___________`
  );
}

export default function ShiftHandoff({ project, shiftNotes, onSaveNotes }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState('');
  const [aiLoading, setAiLoading] = useState(false);

  function handleEdit() {
    setDraft(shiftNotes || '');
    setEditing(true);
  }

  function handleSave() {
    onSaveNotes(draft);
    setEditing(false);
  }

  function handleAIGenerate() {
    if (!editing) {
      setDraft(shiftNotes || '');
      setEditing(true);
    }
    setAiLoading(true);
    setTimeout(() => {
      setDraft(buildAINote(project));
      setAiLoading(false);
    }, 1700);
  }

  let activeSteps = 0, blockedSteps = 0, completedToday = 0;
  for (const ph of project.phases) {
    for (const s of ph.steps) {
      if (s.status === 'active') activeSteps++;
      if (s.status === 'blocked') blockedSteps++;
      if (s.status === 'complete' && s.completedAt && (Date.now() - new Date(s.completedAt)) < 86400000) completedToday++;
    }
  }

  const activePhase = project.phases.find(p => p.status === 'active' || p.status === 'awaiting-signoff');

  return (
    <div style={{
      background: colors.white,
      border: `1px solid ${colors.border}`,
      borderTop: `3px solid ${colors.navy}`,
      borderRadius: 8,
      overflow: 'hidden',
      marginTop: 20,
    }}>
      {/* Header */}
      <div style={{
        padding: '12px 18px',
        borderBottom: `1px solid ${colors.border}`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 8,
        background: colors.navyLight,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span style={{ fontSize: 14 }}>📋</span>
          <span style={{ fontSize: 14, fontWeight: 700, color: colors.textPrimary }}>Shift Handoff Notes</span>
          <span style={{ fontSize: 12, color: colors.textMuted }}>— pass to incoming technician</span>
        </div>

        {/* AI Generate button */}
        <button
          onClick={handleAIGenerate}
          disabled={aiLoading}
          style={{
            background: aiLoading ? colors.navy : `linear-gradient(135deg, #0B1F3A 0%, #1a3566 100%)`,
            color: colors.white,
            border: 'none',
            borderRadius: 5,
            padding: '6px 13px',
            fontSize: 12,
            fontWeight: 600,
            cursor: aiLoading ? 'default' : 'pointer',
            fontFamily: fonts.sans,
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            letterSpacing: 0.2,
            transition: 'opacity 0.15s',
          }}
          onMouseEnter={e => { if (!aiLoading) e.currentTarget.style.opacity = '0.88'; }}
          onMouseLeave={e => { if (!aiLoading) e.currentTarget.style.opacity = '1'; }}
        >
          {aiLoading ? (
            <>
              <div style={{ display: 'flex', gap: 3 }}>
                {[0, 1, 2].map(i => (
                  <div key={i} style={{
                    width: 5, height: 5, borderRadius: '50%', background: colors.white,
                    animation: `aiDotPulse 1.4s ease-in-out ${i * 0.16}s infinite`,
                  }} />
                ))}
              </div>
              Generating…
            </>
          ) : (
            <>✦ Generate with AI</>
          )}
        </button>
      </div>

      {/* Auto status summary */}
      <div style={{
        padding: '12px 18px',
        borderBottom: `1px solid ${colors.border}`,
        background: colors.lightGray,
        display: 'flex',
        gap: 24,
        flexWrap: 'wrap',
      }}>
        <div>
          <div style={{ fontFamily: fonts.mono, fontSize: 11, color: colors.textMuted, marginBottom: 2 }}>CURRENT PHASE</div>
          <div style={{ fontSize: 13, fontWeight: 600, color: colors.textPrimary }}>
            {activePhase ? `Ph.${activePhase.id} — ${activePhase.name}` : 'Complete'}
          </div>
        </div>
        <div>
          <div style={{ fontFamily: fonts.mono, fontSize: 11, color: colors.textMuted, marginBottom: 2 }}>COMPLETED THIS SHIFT</div>
          <div style={{ fontFamily: fonts.mono, fontSize: 13, fontWeight: 700, color: colors.green }}>{completedToday} steps</div>
        </div>
        <div>
          <div style={{ fontFamily: fonts.mono, fontSize: 11, color: colors.textMuted, marginBottom: 2 }}>ACTIVE STEPS</div>
          <div style={{ fontFamily: fonts.mono, fontSize: 13, fontWeight: 700, color: colors.navy }}>{activeSteps}</div>
        </div>
        {blockedSteps > 0 && (
          <div>
            <div style={{ fontFamily: fonts.mono, fontSize: 11, color: colors.textMuted, marginBottom: 2 }}>BLOCKED</div>
            <div style={{ fontFamily: fonts.mono, fontSize: 13, fontWeight: 700, color: colors.red }}>⚠ {blockedSteps} steps</div>
          </div>
        )}
      </div>

      {/* Notes body */}
      <div style={{ padding: '16px 18px' }}>
        {!editing ? (
          <div>
            {shiftNotes ? (
              <div style={{
                fontSize: 12,
                color: colors.textPrimary,
                lineHeight: 1.6,
                padding: '12px 14px',
                background: colors.lightGray,
                borderRadius: 5,
                border: `1px solid ${colors.border}`,
                marginBottom: 12,
                whiteSpace: 'pre-wrap',
                fontFamily: fonts.mono,
              }}>
                {shiftNotes}
              </div>
            ) : (
              <div style={{ fontSize: 13, color: colors.textMuted, fontStyle: 'italic', marginBottom: 12 }}>
                No shift notes yet — add a note manually or let AI generate one based on current project state.
              </div>
            )}
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              <button
                onClick={handleEdit}
                style={{
                  background: colors.navy,
                  color: colors.white,
                  border: 'none',
                  borderRadius: 5,
                  padding: '8px 16px',
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: 'pointer',
                  fontFamily: fonts.sans,
                }}
                onMouseEnter={e => e.currentTarget.style.background = colors.navyMid}
                onMouseLeave={e => e.currentTarget.style.background = colors.navy}
              >
                {shiftNotes ? 'Edit Notes' : '+ Add Shift Notes'}
              </button>
            </div>
          </div>
        ) : (
          <div className="anim-fade-in">
            <textarea
              value={draft}
              onChange={e => setDraft(e.target.value)}
              placeholder="What should the incoming technician know? Include: what was completed, what is in progress, any pending issues, tools/parts needed, next steps…"
              rows={aiLoading ? 4 : 10}
              autoFocus={!aiLoading}
              style={{
                width: '100%',
                padding: '10px 12px',
                fontSize: 12,
                border: `1.5px solid ${aiLoading ? colors.border : colors.navy}`,
                borderRadius: 5,
                resize: 'vertical',
                marginBottom: 10,
                fontFamily: fonts.mono,
                color: colors.textPrimary,
                lineHeight: 1.55,
                outline: 'none',
                background: aiLoading ? colors.lightGray : colors.white,
                transition: 'border-color 0.15s, background 0.15s',
                opacity: aiLoading ? 0.6 : 1,
              }}
            />
            {aiLoading && (
              <div style={{
                fontSize: 12,
                color: colors.navy,
                fontStyle: 'italic',
                marginBottom: 8,
                display: 'flex',
                alignItems: 'center',
                gap: 8,
              }}>
                <div style={{ display: 'flex', gap: 3 }}>
                  {[0, 1, 2].map(i => (
                    <div key={i} style={{
                      width: 5, height: 5, borderRadius: '50%', background: colors.navy,
                      animation: `aiDotPulse 1.4s ease-in-out ${i * 0.16}s infinite`,
                    }} />
                  ))}
                </div>
                AI is generating a shift handoff based on current project state…
              </div>
            )}
            {!aiLoading && (
              <div style={{ display: 'flex', gap: 8 }}>
                <button
                  onClick={handleSave}
                  style={{
                    background: colors.navy, color: colors.white, border: 'none',
                    borderRadius: 5, padding: '8px 18px', fontSize: 13, fontWeight: 700,
                    cursor: 'pointer', fontFamily: fonts.sans,
                  }}
                >
                  Save Handoff Notes
                </button>
                <button
                  onClick={() => setEditing(false)}
                  style={{
                    background: 'none', color: colors.textMuted, border: `1px solid ${colors.border}`,
                    borderRadius: 5, padding: '8px 14px', fontSize: 13, cursor: 'pointer', fontFamily: fonts.sans,
                  }}
                >
                  Cancel
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
